server:
  port: 8484

spring:
    cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka/
