server:
  port: 8183
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Microservices?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: RatingService
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    name: RatingService
    version: 1.0.0
